### ISSUE TITLE
Incorrect groupBlock for elements 113-118

### ISSUE THREAD

**Issue by madsfaerch** [andrejewski/periodic-table#12]
Hey!

First of all, thanks for making this package, I love it.

While colouring elements by groupBlock I noticed that the groupBlock value of elements 113, 114, 115, 116, 117 and 118 don't match what I expected. I checked Wikipedia and confirmed that they do not match Wikipedia's records.

| Element | Atomic Number | Expected Group Block | Actual Group Block |
| ----------|-----------------|------------------------|------------------- |
| [Nihonium](https://en.wikipedia.org/wiki/Nihonium) | 113 | Post-transition metal | Metal |
| [Flerovium](https://en.wikipedia.org/wiki/Flerovium) | 114 | Post-transition metal | Metal |
| [Moscovium](https://en.wikipedia.org/wiki/Moscovium) | 115 | Post-transiton metal | Halogen |
| [Livermorium](https://en.wikipedia.org/wiki/Livermorium) | 116 | Post-transition metal | Noble gas |
| [Tennessine](https://en.wikipedia.org/wiki/Tennessine) | 117 | Post-transition metal | Alkali metal |
| [Oganesson](https://en.wikipedia.org/wiki/Oganesson) | 118 | Noble gas | Alkaline earth metal |

Let me know what you think and if you need a pull request.

Thanks!

**Comment by madsfaerch** [comment]
Further digging:

It seems Lutetium (71) is labelled as transition metal. It is most often labelled as a lanthanoid, but can be labelled as a transition metal, although I most often see it as a lanthanoid.

[Wikipedia](https://en.wikipedia.org/wiki/Lutetium)

**Comment by andrejewski** [comment]
Yes, both of these changes are acceptable. For your PR, please only modify the data.csv. I will build and release the next version from there. Thank you.
