### ISSUE TITLE
Name for Aluminium

### ISSUE THREAD

**Issue by GMartigny** [andrejewski/periodic-table#3]
Hello,

Your chemical elements webservice is great and fill with tasty data.
I just regret that Aluminium is named "Aluminum or Aluminium". It's not really representing the name and can broke display.
![al](https://cloud.githubusercontent.com/assets/2543511/13806380/940c03b0-eb5b-11e5-8e14-2824b48729a7.png)

I think you sould state for one or the other.

**Comment by andrejewski** [comment]
I chose "Aluminum" and submitted the change to NPM, please update your dependencies. Thank you for bringing this to my attention.
