### ISSUE TITLE
Oxygen density

### ISSUE THREAD

**Issue by bdcuck** [andrejewski/periodic-table#6]
The density of oxygen returns as 0 g/cm^3 to me. That can't be right.

**Comment by andrejewski** [comment]
The internet claims the density of Oxygen is 0.001429 g/cm^3, which I assume was rounded down to zero in the original data file. In fact, there are 8 elements with a density of zero. @bdcuck if you had a table of precise densities from a credible publication or source I would be happy to merge those values into the dataset.

**Comment by iamrudra** [comment]
I believe this issue can be closed since at `STP` the density value in the data file holds.

**Comment by andrejewski** [comment]
I will leave this issue open until a credible publication can support an argument's density values one way or the other. I have no problems keeping this open if it allows someone to contribute either more precise values or confirm existing values.

**Comment by bdcuck** [comment]
I can't provide you with a credible source at the moment, but having it set to zero makes doing calculations such as multiplication and division invisible.

**Comment by iamrudra** [comment]
And what kind of credible source are we expecting, @andrejewski ? Just a little curious here....

**Comment by iamrudra** [comment]
I just realized that this one is a little inconsistent. It did not round up the density of Hydrogen - `0.0000899` but it did round it for Oxygen `0.001429` - which happens to be greater than Hydrogen's. And such is the case with many other elements. 

In my opinion, the data needs to be modified - how about we put the density of all elements in the g/cm^3 unit?

**Comment by andrejewski** [comment]
g/cm^3 is good for me. By credible source, I mean a source that a lot people use and could be verified. I'm sure whatever Wolfram uses is fine. Now the work of editing the CSV file is open for completion. Let me know if either of you care to PR or I will keep this issue open and make the changes when I find the time.

**Comment by iamrudra** [comment]
Let me take care of this. :)

**Comment by bdcuck** [comment]
This is pretty inconsistent to do it in kg/m3 all of a sudden.
 Javascript can handle the decimals just fine, there's no need for it to be rounded. I would like to have each value in the same unit, not 8 elements in kg/m^3 and the rest in g/cm^3 .
[http://imgur.com/eQ8MJsm](url)

**Comment by iamrudra** [comment]
Okay to close this?

**Comment by andrejewski** [comment]
Thank you @bdcuck and especially thank you @iamrudra for your contributions!

**Comment by iamrudra** [comment]
Happy to help! :)

**Comment by bdcuck** [comment]
http://imgur.com/owKeG62
Works like a charm, thanks a lot!
