### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by Nysosis** [andrejewski/periodic-table#9]
I've [forked off](https://github.com/Nysosis/periodic-table) and switched the project over to using typescript, that way it's easier and nicer to work with from within other typescript modules.

If it's of interest I can submit a pull request for it?

There is a bit of a breaking change with it, in that to load the 'utils' part, you have to now do 'var util = require('periodic-table/lib/util');`, but I've updated the readme with the correct method, and extended the file with the typescript usage syntax too.

**Comment by andrejewski** [comment]
I appreciate the offer, but I'm not comfortable enough with Typescript to maintain a project using it.

**Comment by Nysosis** [comment]
That's fine, I can totally understand that.
